import json
import time

def convert_cookies():
    try:
        # 读取JSON格式的cookies
        with open('cookies_netscape.txt', 'r', encoding='utf-8') as f:
            cookies = json.load(f)
        
        # 准备Netscape格式的内容
        netscape_cookies = [
            '# Netscape HTTP Cookie File',
            '# https://curl.haxx.se/rfc/cookie_spec.html',
            '# This file was generated by yt-dlp.  Do not edit.',
            ''
        ]
        
        for cookie in cookies:
            domain = cookie.get('domain', '')
            if not domain.startswith('.'):
                domain = '.' + domain
                
            expires = str(int(time.time() + 365*24*60*60))
            
            line = f"{domain}\tTRUE\t/\t"
            line += f"{'TRUE' if cookie.get('secure') else 'FALSE'}\t"
            line += f"{expires}\t"
            line += f"{cookie.get('name', '')}\t"
            line += cookie.get('value', '')
            
            netscape_cookies.append(line)
        
        # 保存为新文件
        with open('cookies.txt', 'w', encoding='utf-8') as f:
            f.write('\n'.join(netscape_cookies))
            
        print("转换完成! 已生成 cookies.txt")
        
    except Exception as e:
        print(f"转换失败: {str(e)}")

if __name__ == "__main__":
    convert_cookies()